Added test case for checking URL has no redaction from GH Actions execution.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,6 +29,9 @@ jobs:
          if [ -z "${{ env.SHARE_URL }}" ]; then
            echo "Share URL is empty"
            exit 1
+         elif [[ "${{ env.SHARE_URL }}" == *"***"* ]]; then
+           echo "Share URL contains invalid characters"
+           exit 1
          else
            echo "Share URL: ${{ env.SHARE_URL }}"
          fi
